artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?id=1LMnQto5TzjZVpXA5RrCmSiMptSV4J9Cf
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  training_data: artifacts/data_ingestion/archive (3)/Training
  testing_data: artifacts/data_ingestion/archive (3)/Testing

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.pth

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.pth

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_training/model.pth
  testing_data: artifacts/data_ingestion/archive (3)/Testing

model_prediction:
  root_dir: artifacts/model_prediction
  model_path: artifacts/model_training/model.pth

deployment: # This section must start at column 0
  root_dir: artifacts/model_deployment # Indented by 2 spaces
  model_path: artifacts/model_training/model.pth # Indented by 2 spaces
  host: 0.0.0.0 # Indented by 2 spaces
  port: 8080 # Indented by 2 spaces
  upload_folder: static/uploads # Indented by 2 spaces
